### ISSUE TITLE
sign up not working 

### ISSUE THREAD

**Issue by sheecegardezi** [yosshipaopao/lucia-sveltekit-d1-example#1]
Sign Up page throws error following error:

```
500
Unexpected token '<', "<!DOCTYPE "... is not valid JSON
```

**Comment by yosshipaopao** [comment]
This is the issue that Lucia-auth is having.
As mentioned in [this document](https://lucia-auth.com/getting-started/#cloudflare)
the free plan's 10ms CPU usage time limit is not sufficient to hash passwords.
This issue does not occur if you use paid plan or try in a local environment.

**Comment by sheecegardezi** [comment]
@yosshipaopao I am on the paided workers plan still getting this error.

**Comment by yosshipaopao** [comment]
I changed my Cloudflare workers to Paid Plan and was able to run it most of the time, but I did see it fail 1 out of 6 tests.
Maybe the Cloudflare turnstile is taking a long time to authenticate.

**Comment by yosshipaopao** [comment]
After making a few changes to the code, I tested it a few more times and it ran fine.
